# Generated by Django 6.0.3 on 2026-04-01 23:26

import rastro.tasks.domain.value_objects
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In_Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('closed', 'Closed')], default=rastro.tasks.domain.value_objects.TaskStatus['OPEN'])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default=rastro.tasks.domain.value_objects.TaskPriority['MEDIUM'])),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.IntegerField()),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
