services:
  postgres:
    image: "postgres:18.3"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql"

  otelcol:
    image: "otel/opentelemetry-collector-contrib:0.148.0"
    ports:
      - "13133:13133"
      - "4318:4318"
      - "4317:4317"
    volumes:
      - "./docker/otel/config.yaml:/etc/otelcol-contrib/config.yaml"

  grafana:
    image: "grafana/grafana:main"
    ports:
      - "7141:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"

volumes:
  postgres_data:
  grafana_data:
