apiVersion: 1

datasources:
  - name: "ClickHouse"
    type: "grafana-clickhouse-datasource"
    access: "proxy"
    jsonData:
      protocol: "${GRAFANA_CLICKHOUSE_PROTOCOL}"
      host: "${GRAFANA_CLICKHOUSE_HOST}"
      port: "${GRAFANA_CLICKHOUSE_PORT}"
      username: "${GRAFANA_CLICKHOUSE_USER}"
    secureJsonData:
      password: "${GRAFANA_CLICKHOUSE_PASSWORD}"
    isDefault: true
